% construct figure
fig = figure('Units','pixels','Position',[randi(100,1,1),randi(100,1,1),600,400]);

container = uipanel('Parent', fig, ...
    'Units','pixels', ...
    'Position',[10 50 300 300], ...
    'BorderType','line');

scroll = bdScroll(container,900,900);
scrollpanel = scroll.panel;
%scrollpanel = container;

% geometry of the panel
panelw = scrollpanel.Position(3);
panelh = scrollpanel.Position(4);

% Begin placing widgets at the top left of scroll panel
yoffset = 25;
boxh = 20;
rowh = 22;            

% SYSTEM title
uicontrol('Style','text', ...
    'String','System', ...
    'HorizontalAlignment','left', ...
    'FontUnits','pixels', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Parent', scrollpanel, ...
    'Position',[10 panelh-yoffset panelw boxh]);

% next row
yoffset = yoffset + rowh;

% sys check box
uicontrol('Style','checkbox', ...
    'String','sys', ...
    'Value', 1, ...
    'Tag', 'bdExportSys', ...
    'HorizontalAlignment','left', ...
    'FontUnits','pixels', ...
    'FontSize',12, ...
    'Parent', scrollpanel, ...
    'Position',[20 panelh-yoffset panelw boxh]);

% next row
yoffset = yoffset + rowh;

% sol check box
uicontrol('Style','checkbox', ...
    'String','sol', ...
    'Tag', 'bdExportSol', ...
    'HorizontalAlignment','left', ...
    'FontUnits','pixels', ...
    'FontSize',12, ...
    'Parent', scrollpanel, ...
    'Position',[20 panelh-yoffset panelw boxh]);

% next row
yoffset = yoffset + 1.25*rowh;

scrollpanel.Position